# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 20:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ra', models.IntegerField(verbose_name='RA Aluno')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('email', models.CharField(max_length=80, verbose_name='E-Mail')),
                ('celular', models.CharField(max_length=11, verbose_name='Celular')),
            ],
        ),
        migrations.CreateModel(
            name='ArquivoQuestao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ArquivoResposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('carga_horaria', models.IntegerField(verbose_name='Carga Horária')),
                ('professor', models.CharField(max_length=50, verbose_name='Coordenador')),
                ('tipo', models.CharField(max_length=50)),
                ('img', models.CharField(blank=True, max_length=255)),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=240, verbose_name='Nome')),
                ('carga_horaria', models.IntegerField(verbose_name='Carga_Horaria')),
                ('teoria', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Teoria')),
                ('pratica', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Pratica')),
                ('ementa', models.TextField(verbose_name='Ementa')),
                ('competencias', models.TextField(verbose_name='Competencias')),
                ('habilidades', models.TextField(verbose_name='Habilidades')),
                ('conteudo', models.TextField(verbose_name='Conteudo')),
                ('bibliografia_basica', models.TextField(verbose_name='Bibliografia Basica')),
                ('bibliografia_complementar', models.TextField(verbose_name='Bibliografia Complementar')),
            ],
        ),
        migrations.CreateModel(
            name='DisciplinaOfertada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('semestre', models.IntegerField(verbose_name='Semestre')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='GradeCurricular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('semestre', models.IntegerField(verbose_name='Semestre')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Curso')),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='Numero')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Curso')),
            ],
        ),
        migrations.CreateModel(
            name='PeriodoDisciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Disciplina')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Periodo')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ra', models.IntegerField(verbose_name='RA')),
                ('apelido', models.CharField(max_length=30, unique=True, verbose_name='Apelido')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('email', models.CharField(max_length=80, verbose_name='E-Mail')),
                ('celular', models.CharField(max_length=11, verbose_name='Celular')),
            ],
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_limite', models.DateField(verbose_name='Data Limite')),
                ('descricao', models.TextField(verbose_name='Descricao')),
                ('data', models.DateField(verbose_name='Data')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Disciplina')),
                ('disciplinaofertada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.DisciplinaOfertada')),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_avaliacao', models.DateField(blank=True, verbose_name='Data Avaliação')),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=4, verbose_name='Nota')),
                ('data_envio', models.DateField(blank=True, verbose_name='Data Envio')),
                ('aluno', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.Aluno')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Disciplina')),
                ('disciplinaofertada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.DisciplinaOfertada')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Questao')),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(max_length=15, verbose_name='Turno')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Disciplina')),
                ('discplinaofertada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.DisciplinaOfertada')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Professor')),
            ],
        ),
        migrations.AddField(
            model_name='resposta',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Turma'),
        ),
        migrations.AddField(
            model_name='questao',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Turma'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='Turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Turma'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Aluno'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='disciplinaofertada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.DisciplinaOfertada'),
        ),
        migrations.AddField(
            model_name='arquivoresposta',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Disciplina'),
        ),
        migrations.AddField(
            model_name='arquivoresposta',
            name='disciplinaofertada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.DisciplinaOfertada'),
        ),
        migrations.AddField(
            model_name='arquivoresposta',
            name='questao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Questao'),
        ),
        migrations.AddField(
            model_name='arquivoresposta',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Turma'),
        ),
        migrations.AddField(
            model_name='arquivoquestao',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Disciplina'),
        ),
        migrations.AddField(
            model_name='arquivoquestao',
            name='disciplinaofertada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.DisciplinaOfertada'),
        ),
        migrations.AddField(
            model_name='arquivoquestao',
            name='questao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Questao'),
        ),
        migrations.AddField(
            model_name='arquivoquestao',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Turma'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='id_curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Curso'),
        ),
    ]
