# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_aluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='img',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
