# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_gradecurricular_periodo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ra', models.IntegerField(verbose_name='RA')),
                ('apelido', models.CharField(max_length=30, unique=True, verbose_name='Apelido')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('email', models.CharField(max_length=80, verbose_name='E-Mail')),
                ('celular', models.CharField(max_length=11, verbose_name='Celular')),
            ],
        ),
    ]
