# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_disciplina'),
    ]

    operations = [
        migrations.CreateModel(
            name='PediodoDisciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Disciplina')),
            ],
        ),
        migrations.RenameField(
            model_name='gradecurricular',
            old_name='id_curso',
            new_name='curso',
        ),
        migrations.RenameField(
            model_name='periodo',
            old_name='id_curso',
            new_name='curso',
        ),
        migrations.AddField(
            model_name='pediododisciplina',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Periodo'),
        ),
    ]
