# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 20:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20171127_1801'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PediodoDisciplina',
            new_name='PeriodoDisciplina',
        ),
    ]
